dist: xenial
language: python
python: 3.7
install:
- pip install pipenv
- pipenv run python setup.py install
script: pipenv run python test_rustyreturn.py
deploy:
  provider: pypi
  user: BTaskaya
  password:
    secure:    IAkSJzDlX2yHv4u9BtuK98BibHT29w2y4Le4PpTgiV44SHHka7j9VrDss18JoBevQu1GriZRfUwqSVznnyTEuV4bVjztVqo4pQuFxzG6Hax5ywHbZ7C8B5mubZymEx8tU6RMKgdgnzNqPYZC5TwO7JQO9IWF3NRTx++Lyz/6kQtemA8wuiMuN2k9TVvnCpAnT+q8vb71WdYKoRVkK+wpEmnTbeAAbWIOUVfogpIaMhAq90u6v9ng4Pw5hlhWGzQriXw4hsbP/DdyQR3bp0EN5/OPHW7ZhIUunVAoZuLxk6ysyiugfwgdNH2xDKhMvw0hC+fNjbxmMo570YHO16CPy9kZqaxSdiY+YC6XqbcuXMB6ozEr7OU5MlmNV+IEICldtvsO2n9YQFDhDN+69zk3X+MtiHu2dFt9ByhdTJPeJRcU70hVXUG3ovDleTOguN/5Z5MY2dYNOsF76QhI12aQ/cdwim6Wr9PHBDkGV7oQgEEo8cZ1GEKJErvSb+i4O4gI5ysMa8UHbhFmbrb7Sas9pAv0Zm90OVV8A9TJiwWUwCBjrCgjPIDdDaMDx4Fe+aPvyu+VVUxARTuJbRz1mEs55UxvIR8sC4rtMspILTgMQZtLTZpfxldD1Tt9oMLK5LnlW5S7KoM/reDD8Yio/14vtr6fTRkQ1KwjvPJcaCOQJ7I=
